//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCalabozosDragones.ServicioCalabozosDragones {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCalabozosDragones")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCalabozosDragones.IGestionCuenta")]
    public interface IGestionCuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/AgregarCuenta", ReplyAction="http://tempuri.org/IGestionCuenta/AgregarCuentaResponse")]
        bool AgregarCuenta(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/AgregarCuenta", ReplyAction="http://tempuri.org/IGestionCuenta/AgregarCuentaResponse")]
        System.Threading.Tasks.Task<bool> AgregarCuentaAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/VerificarInicioSesion", ReplyAction="http://tempuri.org/IGestionCuenta/VerificarInicioSesionResponse")]
        bool VerificarInicioSesion(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/VerificarInicioSesion", ReplyAction="http://tempuri.org/IGestionCuenta/VerificarInicioSesionResponse")]
        System.Threading.Tasks.Task<bool> VerificarInicioSesionAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionCuentaChannel : ClienteCalabozosDragones.ServicioCalabozosDragones.IGestionCuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionCuentaClient : System.ServiceModel.ClientBase<ClienteCalabozosDragones.ServicioCalabozosDragones.IGestionCuenta>, ClienteCalabozosDragones.ServicioCalabozosDragones.IGestionCuenta {
        
        public GestionCuentaClient() {
        }
        
        public GestionCuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionCuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AgregarCuenta(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.AgregarCuenta(cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarCuentaAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.AgregarCuentaAsync(cuenta);
        }
        
        public bool VerificarInicioSesion(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.VerificarInicioSesion(cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarInicioSesionAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.VerificarInicioSesionAsync(cuenta);
        }
    }
}
