//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCalabozosDragones.ServicioCalabozosDragones {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCalabozosDragones")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFoto {
            get {
                return this.IdFotoField;
            }
            set {
                if ((this.IdFotoField.Equals(value) != true)) {
                    this.IdFotoField = value;
                    this.RaisePropertyChanged("IdFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Foto", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCalabozosDragones")]
    [System.SerializableAttribute()]
    public partial class Foto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCalabozosDragones.IGestionCuenta")]
    public interface IGestionCuenta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/AgregarCuenta", ReplyAction="http://tempuri.org/IGestionCuenta/AgregarCuentaResponse")]
        string AgregarCuenta(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/AgregarCuenta", ReplyAction="http://tempuri.org/IGestionCuenta/AgregarCuentaResponse")]
        System.Threading.Tasks.Task<string> AgregarCuentaAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/VerificarInicioSesion", ReplyAction="http://tempuri.org/IGestionCuenta/VerificarInicioSesionResponse")]
        bool VerificarInicioSesion(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/VerificarInicioSesion", ReplyAction="http://tempuri.org/IGestionCuenta/VerificarInicioSesionResponse")]
        System.Threading.Tasks.Task<bool> VerificarInicioSesionAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/ObtenerRuta", ReplyAction="http://tempuri.org/IGestionCuenta/ObtenerRutaResponse")]
        string ObtenerRuta(int idFoto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/ObtenerRuta", ReplyAction="http://tempuri.org/IGestionCuenta/ObtenerRutaResponse")]
        System.Threading.Tasks.Task<string> ObtenerRutaAsync(int idFoto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/ObtenerCuenta", ReplyAction="http://tempuri.org/IGestionCuenta/ObtenerCuentaResponse")]
        ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta ObtenerCuenta(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/ObtenerCuenta", ReplyAction="http://tempuri.org/IGestionCuenta/ObtenerCuentaResponse")]
        System.Threading.Tasks.Task<ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta> ObtenerCuentaAsync(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/ObtenerFoto", ReplyAction="http://tempuri.org/IGestionCuenta/ObtenerFotoResponse")]
        string ObtenerFoto(ClienteCalabozosDragones.ServicioCalabozosDragones.Foto foto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/ObtenerFoto", ReplyAction="http://tempuri.org/IGestionCuenta/ObtenerFotoResponse")]
        System.Threading.Tasks.Task<string> ObtenerFotoAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Foto foto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/ModificarCuenta", ReplyAction="http://tempuri.org/IGestionCuenta/ModificarCuentaResponse")]
        string ModificarCuenta(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuentaModificacion, ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCuenta/ModificarCuenta", ReplyAction="http://tempuri.org/IGestionCuenta/ModificarCuentaResponse")]
        System.Threading.Tasks.Task<string> ModificarCuentaAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuentaModificacion, ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionCuentaChannel : ClienteCalabozosDragones.ServicioCalabozosDragones.IGestionCuenta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionCuentaClient : System.ServiceModel.ClientBase<ClienteCalabozosDragones.ServicioCalabozosDragones.IGestionCuenta>, ClienteCalabozosDragones.ServicioCalabozosDragones.IGestionCuenta {
        
        public GestionCuentaClient() {
        }
        
        public GestionCuentaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionCuentaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCuentaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCuentaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AgregarCuenta(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.AgregarCuenta(cuenta);
        }
        
        public System.Threading.Tasks.Task<string> AgregarCuentaAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.AgregarCuentaAsync(cuenta);
        }
        
        public bool VerificarInicioSesion(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.VerificarInicioSesion(cuenta);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarInicioSesionAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.VerificarInicioSesionAsync(cuenta);
        }
        
        public string ObtenerRuta(int idFoto) {
            return base.Channel.ObtenerRuta(idFoto);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerRutaAsync(int idFoto) {
            return base.Channel.ObtenerRutaAsync(idFoto);
        }
        
        public ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta ObtenerCuenta(string correo, string contrasena) {
            return base.Channel.ObtenerCuenta(correo, contrasena);
        }
        
        public System.Threading.Tasks.Task<ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta> ObtenerCuentaAsync(string correo, string contrasena) {
            return base.Channel.ObtenerCuentaAsync(correo, contrasena);
        }
        
        public string ObtenerFoto(ClienteCalabozosDragones.ServicioCalabozosDragones.Foto foto) {
            return base.Channel.ObtenerFoto(foto);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerFotoAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Foto foto) {
            return base.Channel.ObtenerFotoAsync(foto);
        }
        
        public string ModificarCuenta(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuentaModificacion, ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.ModificarCuenta(cuentaModificacion, cuenta);
        }
        
        public System.Threading.Tasks.Task<string> ModificarCuentaAsync(ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuentaModificacion, ClienteCalabozosDragones.ServicioCalabozosDragones.Cuenta cuenta) {
            return base.Channel.ModificarCuentaAsync(cuentaModificacion, cuenta);
        }
    }
}
